#!/usr/bin/env python3
import click
from game import game

@click.command()
@click.option('--hard-mode', is_flag=True, help='Enable hard mode that uses all printable ASCII characters.')
@click.version_option(version='0.2.1')
@click.help_option('--help', '-h')

def main(hard_mode):
    """A simple memory game utilizing the keyboard"""
    if hard_mode:
        game(True)
    else:
        game(False)

if __name__ == '__main__':
    main()